import { IntegratedSystemConfig } from '../types/config';

export const DEFAULT_SYSTEM_CONFIG: IntegratedSystemConfig = {
  c2_security: {
    rhosts: ['192.168.1.100', '10.0.4.15'],
    rport: 443,
    lhost: '10.0.0.1',
    lport: 8443,
    beacon_interval_seconds: 60.0,
    jitter_percentage: 20.0,
    user_agent_string: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 EnterpriseSec/3.4',
    payload_type: 'raw',
    encryption_algorithm: 'AES-256-GCM',
    encryption_key: 'a_very_secret_key_32_bytes_long!!',
    kill_date: 1790000000,
    max_retry_attempts: 5,
    malleable_profile_hash: 'a1b2c3d4e5f67890a1b2c3d4e5f67890',
    dns_fallback_domain: 'fallback.internal-enterprise.corp',
    process_injection_target: 'explorer.exe',
    named_pipe_name: 'corp_ai_mesh_pipe',
    tls_certificate_thumbprint: '9f8e7d6c5b4a32109f8e7d6c5b4a32109f8e7d6c',
    proxy_url: null,
    working_hours_utc: '01:00-11:00', // Matches 08:00 - 18:00 Bangkok Time (UTC+7)
    memory_alloc_flags: 'PAGE_EXECUTE_READWRITE',
    stage_encoding: 'base64_xor',
    stager_url: 'https://cdn.internal-enterprise.corp/stager.bin',
    obfuscation_level: 3,
    anti_analysis_flags: ['AntiDebug', 'SandboxCheck', 'HypervisorDetect'],
  },

  rf_subghz: {
    frequency_mhz: 433.92,
    te_microseconds: 350.0,
    bit_length: 64,
    pulse_multiplier: 1.5,
    modulation_type: 'FSK',
    preamble_length_bits: 32,
    sync_word: '0x2D4D',
    bandwidth_khz: 125.0,
    tx_power_dbm: 14.0,
    deviation_khz: 25.0,
    data_rate_bps: 9600.0,
    crc_polynomial: 'CRC-16-CCITT',
    lora_sf: 7,
    lora_coding_rate: '4/5',
    rssi_threshold_dbm: -105.0,
    snr_db: 7.5,
    antenna_gain_dbi: 2.15,
    frequency_hop_channels: [433.2, 433.5, 433.8, 434.1],
    manchester_encoding: true,
    duty_cycle_limit_pct: 1.0,
    center_frequency_offset_hz: 0.0,
    rx_gain_db: 18.0,
    packet_preamble_pattern: '10101010',
    fec_scheme: 'Hamming(7,4)',
  },

  web_security: {
    redirect_url: 'https://internal-portal.enterprise.corp/auth/callback',
    allowed_domains: ['internal-portal.enterprise.corp', 'ai-gateway.enterprise.corp', 'localhost'],
    query_params: { scope: 'openid profile internal_ai', state: 'anti_csrf_mesh_token' },
    cors_origins: ['https://internal-portal.enterprise.corp'],
    content_security_policy: "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; font-src 'self' fonts.gstatic.com;",
    cookie_same_site: 'Strict',
    cookie_secure_flag: true,
    cookie_http_only: true,
    jwt_signing_algorithm: 'RS256',
    jwt_expiration_seconds: 3600,
    max_request_body_bytes: 10485760, // 10MB
    allowed_http_methods: ['GET', 'POST', 'OPTIONS'],
    rate_limit_ip_rpm: 120,
    csrf_token_hash: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
    x_frame_options: 'DENY',
    hsts_max_age_seconds: 31536000,
    ssrf_blocked_cidrs: ['127.0.0.0/8', '169.254.169.254/32', '10.0.0.0/8'],
    sql_injection_filter_pattern: '(?i)(union\\s+select|select\\s+.*\\s+from|insert\\s+into|drop\\s+table)',
    xss_sanitization_mode: 'strict',
    tls_min_version: 'TLS1.3',
    waf_rule_set_id: 'OWASP_CRS_v3.3_PARANOIA_2',
    strict_transport_security: true,
    referrer_policy: 'no-referrer',
  },

  database_engine: {
    db_host: '10.0.2.20',
    db_port: 5432,
    db_name: 'enterprise_ai_vault',
    db_user: 'svc_ai_zero_trust',
    max_connections: 200,
    instances: 4,
    min_idle_connections: 20,
    connection_timeout_ms: 3000,
    query_timeout_seconds: 5.0,
    idle_in_transaction_timeout_ms: 10000,
    statement_cache_size: 1000,
    ssl_mode: 'verify-full',
    read_replica_hosts: ['10.0.2.21', '10.0.2.22'],
    redis_db_index: 0,
    redis_cluster_nodes: ['redis://10.0.3.10:6379', 'redis://10.0.3.11:6379'],
    migration_version: '2026.04.1-rc3',
    deadlock_detect_interval_ms: 200,
    wal_level: 'replica',
    max_prepared_transactions: 100,
    auto_explain_min_duration_ms: 1000,
    or_mapper_lazy_load: true,
    connection_lifetime_sec: 3600,
    connection_retry_backoff_ms: 500,
  },

  infrastructure: {
    app_env: 'production',
    secret_key: 'corp_master_crypto_key_entropy_high_32!',
    database_url: 'postgresql://svc_ai_zero_trust:masked_secret@10.0.2.20:5432/enterprise_ai_vault?sslmode=verify-full',
    log_level: 'INFO',
    cluster_region: 'asia-southeast1',
    k8s_namespace: 'internal-ai-governance',
    pod_cpu_limit: '4000m',
    pod_memory_limit_mb: 8192,
    autoscaling_min_replicas: 2,
    autoscaling_max_replicas: 16,
    health_check_path: '/healthz',
    graceful_shutdown_timeout_sec: 30,
    tracer_endpoint: 'http://otel-collector.observability:4318',
    metrics_port: 9090,
    dns_resolvers: ['10.0.0.2', '10.0.0.3'],
    storage_bucket_name: 'corp-private-embeddings-vault',
    storage_access_key_id: 'AKIA_CORP_INTERNAL_SEC_01',
    cdn_edge_zone_id: 'zone_asia_bkk_01',
    feature_flags_json: {
      enable_rag_rerank: true,
      enable_voice_realtime: true,
      strict_zero_trust_eval: true,
      dlp_active_blocking: true,
    },
    ci_build_commit_sha: 'e92fc71a0b59bcfc7075a31a9809623e1208a54d',
    smtp_relay_host: 'mail-relay.internal-enterprise.corp',
    container_registry_url: 'cr.internal-enterprise.corp/ai-mesh/runtime:v2.4',
    deployment_strategy: 'RollingUpdate',
  },

  ai_engine: {
    temperature: 0.7,
    top_p: 0.9,
    learning_rate: 0.001,
    top_k: 40,
    max_tokens: 2048,
    presence_penalty: 0.0,
    frequency_penalty: 0.0,
    stop_sequences: ['<|im_end|>', '</s>', 'User:'],
    embedding_dimension: 1536,
    vector_distance_metric: 'cosine',
    chunk_size_tokens: 512,
    chunk_overlap_tokens: 64,
    retrieval_k_documents: 5,
    rerank_score_threshold: 0.7,
    batch_size: 32,
    context_window_limit: 128000,
    model_name_version: 'Enterprise-Llama3-70B-Instruct-v2',
    seed: 42,
    quantization_bits: 'FP16',
    rag_hybrid_alpha: 0.5,
    llm_router_provider: 'internal_vllm_gateway',
    prompt_caching_enabled: true,
    embedding_model_name: 'text-embedding-3-large',
  },

  voice_assistant: {
    stt_engine: 'whisper-v3-enterprise',
    tts_engine: 'elevenlabs-private-node',
    wake_word: 'Hey AI',
    sample_rate_hz: 16000,
    audio_channels: 1,
    voice_id: 'th-TH-Standard-A',
    silence_threshold_seconds: 1.5,
    enable_audio_streaming: true,
  },

  bot_zero_trust: {
    bot_id: 'bot-sec-mesh-th-09',
    agent_type: 'enterprise_ai_operator',
    allowed_tools: ['rag_knowledge_search', 'llm_param_calculator', 'infra_telemetry', 'dlp_inspector'],
    rate_limit_rpm: 60,
    max_tokens_per_call: 4096,
    daily_budget_usd: 150.0,
    ttl_seconds: 3600,
    ip_whitelist: ['10.0.0.0/8', '192.168.0.0/16', '127.0.0.1'],
    device_posture_hash: 'd41d8cd98f00b204e9800998ecf8427e0123456789abcdef',
    did_uri: 'did:corp:node:th-bkk-datacenter-01',
    network_reputation_score: 0.94,
    overlay_ip_address: '100.64.12.8',
    behavioral_anomaly_score: 0.05,
    dynamic_trust_score: 0.91,
    required_mfa_level: 'fido2_webauthn',
    vector_embedding: new Array(128).fill(0.025),
    federated_node_id: 'cluster-mesh-edge-th',
    ephemeral_mesh_token: 'mtk_live_enterprise_mesh_session_99x7',
    m2m_client_id: 'corp-ai-assistant-client-id',
    m2m_client_secret_hash: '5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8',
    trusted_identity_provider: 'https://sso.enterprise.corp/oauth2/v1',
    session_risk_level: 'low',
    attestation_payload: 'tpm2_pcr_quote_verified_sha256:7f83b1657ff1fc53b92dc18148a1d65dfc2d4b1fa3d677284addd200126d9069',
    mesh_mtls_cert_serial: '55:34:AA:99:BC:12:00:FE',
    data_sovereignty_region: 'TH-Thailand-OnPrem',
    zero_trust_policy_version: 'v4.2.0-enforced',
    continuous_eval_interval_sec: 30,
    isolation_sandbox_mode: false,
    audit_log_stream_topic: 'corp-ai-audit-logs.v1',
  },
};

export const PRESET_CONFIGS = [
  {
    id: 'enterprise_70b',
    name: 'Enterprise 70B (High Security & Privacy)',
    description: 'สเปคสำหรับองค์กรขนาดใหญ่ โมเดล 70B รันบน On-Premise GPU Cluster ปลอดภัยสูงสุด',
    model: 'Enterprise-Llama3-70B-Instruct-v2',
    quantization: 'FP16' as const,
    paramsB: 70,
    context: 128000,
    temp: 0.7,
    topP: 0.9,
    trustScore: 0.94,
    dailyBudget: 250,
  },
  {
    id: 'edge_8b',
    name: 'Internal Edge 8B (Low Resource & Fast Voice)',
    description: 'สเปคเบา สำหรับเครื่องเซิร์ฟเวอร์สำนักงานสาขา หรือ Edge Kiosk ตอบสนองด้วยเสียงรวดเร็ว',
    model: 'Enterprise-Llama3-8B-Voice-Speed',
    quantization: '4-bit' as const,
    paramsB: 8,
    context: 32000,
    temp: 0.5,
    topP: 0.85,
    trustScore: 0.88,
    dailyBudget: 50,
  },
  {
    id: 'deep_rag_32b',
    name: 'Corporate RAG & Research 32B (Qwen/DeepSeek)',
    description: 'วิเคราะห์เอกสารความลับ ค้นหาข้อมูลนโยบายองค์กร Chunk Size ขนาดใหญ่และ Reranker',
    model: 'Enterprise-Qwen2.5-32B-RAG',
    quantization: 'INT8' as const,
    paramsB: 32,
    context: 64000,
    temp: 0.3,
    topP: 0.8,
    trustScore: 0.96,
    dailyBudget: 180,
  },
  {
    id: 'airgap_kiosk',
    name: 'Air-Gapped Secure Voice Kiosk (Strict Zero-Trust)',
    description: 'ตู้คีออสอัจฉริยะแบบตัดอินเทอร์เน็ตสมบูรณ์แบบ ทำงานด้วยเสียง 100% ป้องกันข้อมูลรั่วไหลเด็ดขาด',
    model: 'AirGap-Local-Voice-7B',
    quantization: '4-bit' as const,
    paramsB: 7,
    context: 16000,
    temp: 0.6,
    topP: 0.85,
    trustScore: 0.99,
    dailyBudget: 30,
  },
];
